"""RIO live: one speech-to-speech session, and the things she can reach for.

WHAT CHANGED, AND WHAT DID NOT
------------------------------
The conversation path used to be three models in a line — Whisper heard the
driver, a chat model thought, ElevenLabs spoke — and every turn paid all three
latencies in series, with a push-to-talk button holding the whole thing
together. The realtime model is all three at once: the driver's audio goes in,
RIO's audio comes out, and either of them can interrupt the other mid-word.

What did NOT change is everything that speaks deterministically. Headway
warnings, vehicle-health announcements and navigation instructions are
generated by policy code, spoken from fixed tables, and arbitrated exactly as
before. No model is anywhere near them, and this file must never become a way
in. RIO's live voice is conversation, and conversation is the tier that yields.

THE ESCALATION
--------------
Some questions want more than a fast conversational model should attempt: what
is actually open at this hour, what a fault code really means, anything needing
the web or a chain of reasoning. For those the realtime session calls ONE tool,
which asks the reasoning model and hands back text.

The driver never learns any of this happened. There is no second voice, no
"let me ask my research model" — RIO says something while it runs, then speaks
the answer as her own. And if it fails, times out, or is switched off, she
carries on and answers from what she already has: the tool returning
`ok: false` is an ordinary outcome the instructions tell her how to handle,
not an error the driver hears about.

AND ONE THING SHE DOES
----------------------
The rest of her tools are reads: the camera, the route, the car, the reasoning
model. `start_navigation` is not. Asked to be taken somewhere, RIO sets the
destination herself, through the same path the dashboard's destination box
uses, and confirms it — where she used to describe the route and tell the
driver to set it themselves.

That is not a crack in the rule above. Announcing is speaking unasked;
routing is doing what was asked. The turns are the part that does not move:
navigation calls those, out loud, from its own tables, and nothing here may
become a way in.
"""
import json
import os
import threading
import time
from typing import Optional

from openai import OpenAI

import config

_client: Optional[OpenAI] = None
_client_lock = threading.Lock()

# The one tool the live session can call. Named for what the DRIVER would call
# it, not for the model behind it — nothing in the session's vocabulary should
# make a second model visible.
TOOL_NAME = "deep_dive"

# The second tool: RIO's eyes. The camera pipeline already exists and already
# answers questions about what is out of the window (docs/visual_qa.md) — it
# picks the clearest recent frame, resolves "the black one" to a tracked
# object, crops it and asks a multimodal model. None of that is reachable from
# a live audio session unless the session can ask for it, and a RIO who answers
# "what's that car?" from a conversational prior instead of from the camera is
# worse than one who says she cannot see it.
LOOK_TOOL_NAME = "look"

# The other two things a driver asks about that RIO cannot answer from a
# conversation prior: where we are going, and how the car is. Both already have
# a source of truth in this system and neither of them is the model.
NAV_TOOL_NAME = "nav_status"
VEHICLE_TOOL_NAME = "vehicle_status"

# ...and the one thing on this list she DOES rather than reports. A driver who
# says "take me to the Getty" has not asked for information about the Getty;
# they have asked to be taken there, and until this existed the only honest
# thing RIO could do with that was describe the place and tell them to type it
# into the panel themselves. Setting a destination was already a solved problem
# on this page — the box resolves it, loads the route and starts the tracker —
# and this is that same path with RIO's voice as the caller. It is answered in
# the browser, where the route and the tracker live.
NAVIGATE_TOOL_NAME = "start_navigation"

TOOL_SCHEMA = {
    "type": "function",
    "name": TOOL_NAME,
    "description": (
        "Think harder about something, or look it up. Use this when the driver "
        "asks something that needs current information (opening hours, prices, "
        "news, anything that changes), specific factual research, or careful "
        "multi-step reasoning you cannot do well in a couple of seconds. Do NOT "
        "use it for chat, for anything about the car's own sensors, or for "
        "anything about the route — those are already answered elsewhere. Say a "
        "short natural line to the driver before calling it, because it takes a "
        "few seconds."
    ),
    "parameters": {
        "type": "object",
        "properties": {
            "question": {
                "type": "string",
                "description": "The question to work on, written out in full.",
            },
            "context": {
                "type": "string",
                "description": (
                    "Anything from the conversation needed to make sense of it "
                    "— what the driver actually meant, what was already said."
                ),
            },
        },
        "required": ["question"],
        "additionalProperties": False,
    },
}

LOOK_SCHEMA = {
    "type": "function",
    "name": LOOK_TOOL_NAME,
    "description": (
        "Look through the car's forward camera and answer a question about what "
        "is actually out there right now. Use this for ANY question about the "
        "road, other vehicles, signs, buildings or surroundings — 'what's that "
        "car', 'what does that sign say', 'what colour is the one on the left', "
        "'what do you see'. You cannot see anything without calling this: if a "
        "question is about the world outside the car, call it rather than "
        "guessing. It takes a couple of seconds."
    ),
    "parameters": {
        "type": "object",
        "properties": {
            "question": {
                "type": "string",
                "description": (
                    "The driver's question about what is visible, in their own "
                    "words as far as possible — the camera pipeline resolves "
                    "phrases like 'the black one on the left' itself."
                ),
            },
        },
        "required": ["question"],
        "additionalProperties": False,
    },
}

NAV_SCHEMA = {
    "type": "function",
    "name": NAV_TOOL_NAME,
    "description": (
        "Where the drive currently stands: destination, ETA, the next maneuver "
        "and how far away it is, whether we are on route, and whether GPS is "
        "healthy. Call this for ANY question about the route — where are we "
        "going, how long left, what's the next turn, are we lost, did we miss "
        "it. You do not otherwise know any of this. It returns instantly.\n"
        "This is for ANSWERING questions. It is not a cue to announce the turn: "
        "the navigation system calls turns itself, out loud, and you must not."
    ),
    "parameters": {"type": "object", "properties": {}, "additionalProperties": False},
}

VEHICLE_SCHEMA = {
    "type": "function",
    "name": VEHICLE_TOOL_NAME,
    "description": (
        "How the car itself is: live sensor summary, anything the vehicle's "
        "computer has reported, anything RIO has observed, and any fault codes "
        "including ones detected but not yet confirmed. Call this for ANY "
        "question about the car — the tires, the engine, oil, coolant, the "
        "battery, warning lights, 'is everything okay', 'is anything wrong'. "
        "You do not otherwise know any of it, and you must never guess at a "
        "number. It returns instantly.\n"
        "This is for ANSWERING questions. Health announcements are made by the "
        "car itself; you do not make them."
    ),
    "parameters": {"type": "object", "properties": {}, "additionalProperties": False},
}

NAVIGATE_SCHEMA = {
    "type": "function",
    "name": NAVIGATE_TOOL_NAME,
    "description": (
        "Start navigating somewhere. This is how the driver actually gets "
        "taken to a place: 'take me to the Getty', 'navigate to LAX', "
        "'let's go to Ralphs', 'directions to 1200 Getty Center Drive'. It "
        "resolves the destination and makes the route live — the same thing "
        "that happens when a destination is typed into the panel — so you "
        "never tell the driver to set it themselves. Call it as soon as they "
        "ask; do not ask permission first.\n"
        "It can come back asking WHICH ONE: more than one place answers to "
        "what they said. Put that question to the driver in your own words and "
        "call this again with their answer. Never pick one yourself.\n"
        "Setting the route does not make you the voice of the turns. The "
        "navigation system still calls those out loud itself, and you still "
        "must not."
    ),
    "parameters": {
        "type": "object",
        "properties": {
            "destination": {
                "type": "string",
                "description": (
                    "The place the driver asked for, in their own words. "
                    "Leading phrases like 'take me to' are stripped for you, "
                    "so the sentence as they said it is fine. If they have "
                    "just chosen between places you offered, pass the full "
                    "name of the one they chose."
                ),
            },
        },
        "required": ["destination"],
        "additionalProperties": False,
    },
}

# Appended to RIO's own personality prompt. Only the things that are true of a
# LIVE session and not of the text path: how to be interrupted, how long to
# talk for, and when to reach for the tool.
LIVE_ADDENDUM = """
YOU ARE LIVE, IN A MOVING CAR.

You are speaking out loud, in real time, to someone who is driving. Everything
in your character stays exactly as it is; these are the things that are only
true when you are being heard rather than read:

- Be brief by default. One or two sentences. The driver can always ask for
  more, and while you are talking they cannot hear the road.
- Expect to be interrupted, and stop cleanly when you are. Do not restate what
  you had already said — pick up from what they just asked.
- Other voices will cut you off mid-sentence: a gap warning, a tire fault, a
  turn instruction. That is correct and it is not your business. Do not
  apologise for it, do not fight it, do not repeat yourself afterwards unless
  the driver asks.
YOU ANSWER. YOU DO NOT ANNOUNCE.

This is the line that matters most, and it is not about tone — it is about two
voices saying the same thing at once. The car announces things on its own:
turn instructions, health warnings, hazard alerts. Those come from the car's own
systems, in your voice, and they are already handled.

So: never announce a turn, a fault, or a hazard on your own initiative. Not
when a tool result shows one. Not when you think it would be helpful. If
nav_status tells you a turn is coming in four seconds, that is CONTEXT for
answering the driver — it is not a cue to say "turn left here", because the
navigation system is about to say exactly that and you would be talking over
it.

Asked, you answer freely: "where are we going", "how far", "what's the next
turn", "is everything okay with the car". Unasked, you say nothing about any of
it.

Being asked to DO something is not an exception to this, it is the other half
of it. "Take me to the Getty" is not an announcement waiting to happen, it is
an instruction, and carrying it out is answering. So you start routes. What you
still never do is call the turns along the way.

- Never invent anything about the car, the route, or the road. You have tools
  for all three and they are the only way you know any of it — including
  setting a destination, which is a tool and not something you can ask the
  driver to do for you.
- You cannot see. The camera is a tool — `look` — and it is the only way you
  know what is out of the window. Anything about the road, another vehicle, a
  sign, a building or the surroundings goes through it, every time, even when
  you think you can guess from what was said a moment ago. A confident answer
  about a car you did not look at is the worst thing you can do here.
- Numbers are spoken, not written: "twenty-nine P S I", not "29 PSI".

WHEN THE DRIVER ASKS ABOUT SOMETHING OUTSIDE THE CAR

Use the look tool, and say something first — "let me look" — because it takes a
couple of seconds. What comes back is short factual background: describe it in
your own words, as you would anything else. Answer with what it gives you and
nothing more; if it says it cannot see, or asks which one the driver meant, say
that, in your own words.

WHEN THE DRIVER ASKS TO GO SOMEWHERE

"Take me to the Getty." "Navigate to LAX." "Let's go get coffee at the Ralphs
on Lincoln." Call start_navigation, straight away. It sets the destination and
starts the route — the same route the panel would have loaded — and it is
YOURS. Never tell the driver to type it in, to set it on the screen, or to do
anything about it themselves. That was the old arrangement and it was a bad
one: you were describing a drive you would not begin.

Then say one short line confirming it, in your own words: "Getting you to the
Getty — about eighteen minutes." Two rules about that line and nothing else is
prescribed: use the destination name the tool hands back, spelled its way
rather than the way you heard it — LAX and LAS are one letter apart and only
one of them is where they are going — and say it once.

If it comes back asking WHICH ONE, it has found more than one place that
answers to what they said, and choosing between them is not yours to do. Ask —
name them, briefly — and when the driver answers, call start_navigation again
with what they chose. If it could not find the place at all, say so and ask
them to put it another way. If the route itself failed, say that plainly too.
None of those three are cues to hand the job back to the driver.

WHEN THE DRIVER ASKS ABOUT THE ROUTE, OR ABOUT THE CAR

Use nav_status or vehicle_status. Both are instant, so just call them — no
holding line needed. Never answer either kind of question from memory or from
what you were told earlier in the drive: the whole point of them is that the
answer changes while you are talking.

Answering about the car, three rules that are not negotiable:
  * Say only what the data supports. If a field is not there, you do not know
    it. No estimated pressures, no invented mileage, no "probably fine".
  * Keep the provenance. Something the vehicle's own computer reported and
    something RIO noticed are different claims and must sound different.
  * A code that is detected but NOT CONFIRMED is exactly that. Say it that way —
    "the car has picked something up but hasn't confirmed it yet" — and never
    upgrade it to a fault.

WHEN A QUESTION NEEDS MORE THAN A QUICK ANSWER

Use the deep_dive tool. Say something natural first — "let me check", "give me
a second" — then answer in your own voice when it comes back. Never mention the
tool, and never suggest that anything other than you answered.

If it comes back with ok: false, do not mention that either. Just answer as
well as you can from what you already know, or say plainly that you cannot find
that out right now.
"""


# ---------------------------------------------------------------------------
# Deterministic speech, in RIO's own voice
# ---------------------------------------------------------------------------
# Headway warnings, vehicle-health announcements and navigation instructions are
# written by policy code and must be spoken WORD FOR WORD. They are not asked
# for, they are dictated: the model is a voice here and nothing else.
#
# The mechanism is an out-of-band response — `conversation: "none"` — so a
# dictated line never enters the conversation history. That matters more than
# it looks: a warning that landed in the transcript would be something RIO could
# later refer back to, agree with, or be asked about, and the line is a fact
# about the car rather than a thing she said.
#
# Verbatim is REQUESTED here and VERIFIED in the tests (tools/realtime_selftest.py
# transcribes the audio that comes back and compares it with what was asked
# for). A model can always paraphrase; what stops that shipping is the check,
# not the sentence below.
VERBATIM_INSTRUCTION = (
    "Read the text below out loud, exactly as written, word for word.\n"
    "Add nothing. Remove nothing. Do not rephrase, summarise, translate, greet, "
    "acknowledge, comment, or continue past the end of it.\n"
    "It is not addressed to you and it is not a question for you to answer: it "
    "is a line for you to read.\n"
    "Read it in your normal voice, at a normal pace.\n\n"
    "TEXT:\n"
)


def verbatim_response(text: str) -> dict:
    """The `response.create` payload that speaks one deterministic line.

    Out of band, audio only, and carrying its own instructions so it is
    unaffected by whatever the session was told at the start.
    """
    return {
        "conversation": "none",
        "output_modalities": ["audio"],
        "instructions": VERBATIM_INSTRUCTION + (text or "").strip(),
    }


def render_speech(text: str, timeout_s: float = 30.0) -> dict:
    """Speak one line through a short-lived session and return the audio.

    Server-side, synchronous, and not on any live path — this exists to
    PRE-RENDER the critical clips in the same voice the live session uses, and
    to give the tests something to transcribe. The car never calls it: in the
    car the browser already holds a session and dictates into that one.

    Returns {ok, wav, transcript, ms} — `transcript` being the model's own
    account of what it said, which is the first half of the verbatim check.
    """
    import base64
    import io
    import wave

    line = (text or "").strip()
    if not line:
        return {"ok": False, "note": "no text"}
    t0 = time.time()
    pcm = bytearray()
    transcript = ""
    try:
        with client().realtime.connect(model=config.OPENAI_REALTIME_MODEL) as conn:
            conn.session.update(session={
                "type": "realtime",
                "output_modalities": ["audio"],
                "audio": {"output": {
                    "voice": config.OPENAI_REALTIME_VOICE,
                    "format": {"type": "audio/pcm", "rate": 24000},
                }},
            })
            conn.response.create(response=verbatim_response(line))
            for event in conn:
                if event.type == "response.output_audio.delta":
                    pcm += base64.b64decode(event.delta)
                elif event.type == "response.output_audio_transcript.done":
                    transcript = event.transcript or ""
                elif event.type == "response.done":
                    break
                elif event.type == "error":
                    return {"ok": False, "note": str(getattr(event, "error", "error"))}
                if (time.time() - t0) > timeout_s:
                    return {"ok": False, "note": "timeout"}
    except Exception as e:
        print(f"[realtime] render failed: {type(e).__name__}: {e}", flush=True)
        return {"ok": False, "note": f"{type(e).__name__}"}
    if not pcm:
        return {"ok": False, "note": "no audio"}
    buf = io.BytesIO()
    with wave.open(buf, "wb") as w:
        w.setnchannels(1)
        w.setsampwidth(2)
        w.setframerate(24000)
        w.writeframes(bytes(pcm))
    return {"ok": True, "wav": buf.getvalue(), "transcript": transcript,
            "ms": round((time.time() - t0) * 1000, 1),
            "seconds": round(len(pcm) / 48000.0, 2)}


def client() -> OpenAI:
    global _client
    with _client_lock:
        if _client is None:
            _client = OpenAI()
        return _client


def instructions() -> str:
    """RIO's personality, plus what is only true when she is being heard."""
    return (config.SYSTEM_PROMPT or "").rstrip() + "\n\n" + LIVE_ADDENDUM.strip()


def session_config() -> dict:
    """The live session, as the API wants it.

    Two choices worth stating:

    `turn_detection` is server VAD with interruption ON. That is barge-in: the
    driver starts talking, the model stops, immediately, without waiting for a
    button. In a car that is not a nicety — it is how you stop a machine that
    is mid-paragraph when you need to say something.

    `transcription` names the SAME Whisper model the rest of the system uses.
    The live session does not need a transcript to work, but the session log,
    /last_talk and every review of a drive do, and having them come from a
    different model than every other transcript in the JSONL would be a quiet
    way to make two records that disagree.
    """
    return {
        "type": "realtime",
        "model": config.OPENAI_REALTIME_MODEL,
        "instructions": instructions(),
        "audio": {
            "input": {
                "transcription": {"model": config.OPENAI_STT_MODEL},
                "turn_detection": {
                    "type": "server_vad",
                    "create_response": True,
                    "interrupt_response": True,
                },
            },
            "output": {"voice": config.OPENAI_REALTIME_VOICE},
        },
        "tools": [TOOL_SCHEMA, LOOK_SCHEMA, NAV_SCHEMA, VEHICLE_SCHEMA,
                  NAVIGATE_SCHEMA],
        "tool_choice": "auto",
    }


def mint_client_secret() -> dict:
    """An ephemeral key for the browser, and nothing else.

    The browser needs credentials to open a WebRTC connection to the model, and
    the account key is not a thing to hand it. This mints a short-lived secret
    scoped to one session, which is the same discipline every other key on this
    page follows: routing, geocoding and TTS all go through the server, and the
    one key a browser is allowed to see is the Maps render key, which cannot do
    anything but draw a map.
    """
    cfg = session_config()
    secret = client().realtime.client_secrets.create(session=cfg)
    data = secret.model_dump()
    return {
        "client_secret": data.get("value"),
        "expires_at": data.get("expires_at"),
        "model": config.OPENAI_REALTIME_MODEL,
        "voice": config.OPENAI_REALTIME_VOICE,
        "tool": TOOL_NAME,
        "tools": [t["name"] for t in cfg["tools"]],
        # Dictation policy travels WITH the session, so the browser holds no
        # copy of the verbatim instruction that could drift from this one. What
        # RIO is told to read a warning as is decided here, once.
        "verbatim_instruction": VERBATIM_INSTRUCTION,
        "speech_enabled": bool(config.REALTIME_SPEECH_ENABLED),
        "speech_channels": dict(config.REALTIME_SPEECH_CHANNELS),
        "speak_timeout_ms": int(config.REALTIME_SPEAK_TIMEOUT_MS),
    }


def escalate(question: str, context: str = "", timeout_s: Optional[float] = None) -> dict:
    """The deep_dive tool: ask the reasoning model, hand back text.

    Never raises. Every failure — a timeout, an outage, a refusal, a model id
    that is not on this account — returns `ok: false` with a short note, and the
    session's instructions tell RIO what to do with that: carry on. A driver
    should never be able to tell the difference between "the reasoning model was
    unavailable" and "RIO decided to answer this one herself".

    The result is text for RIO to speak in her own words, so it is asked for as
    speech: no markdown, no lists, no citations read aloud like a bibliography.
    """
    q = (question or "").strip()
    if not q:
        return {"ok": False, "note": "no question"}
    timeout = float(config.REALTIME_TOOL_TIMEOUT_S if timeout_s is None else timeout_s)

    prompt = q if not context else f"{q}\n\nContext from the conversation: {context}"
    tools = [{"type": "web_search"}] if config.REALTIME_WEB_SEARCH else []
    t0 = time.time()
    try:
        # `with_options` rather than a thread: the SDK's own timeout aborts the
        # request, where a thread would leave it running and still billed.
        resp = client().with_options(timeout=timeout).responses.create(
            model=config.OPENAI_REASONING_MODEL,
            instructions=(
                "You are the research and reasoning step behind a car "
                "assistant's spoken answer. Answer the question directly and "
                "completely, in plain prose meant to be READ ALOUD: no "
                "markdown, no bullet points, no headings, no URLs, no "
                "citations. Two or three sentences unless the question genuinely "
                "needs more. If the answer depends on something you cannot "
                "verify, say so in the answer itself rather than hedging around "
                "it."
            ),
            input=prompt,
            tools=tools,
            max_output_tokens=int(config.REALTIME_TOOL_MAX_OUTPUT_TOKENS),
        )
    except Exception as e:
        took = round((time.time() - t0) * 1000, 1)
        print(f"[realtime] deep_dive failed after {took} ms: "
              f"{type(e).__name__}: {e}", flush=True)
        return {"ok": False, "note": f"{type(e).__name__}", "took_ms": took}

    text = (getattr(resp, "output_text", "") or "").strip()
    took = round((time.time() - t0) * 1000, 1)
    if not text:
        return {"ok": False, "note": "empty answer", "took_ms": took}
    return {"ok": True, "answer": text, "took_ms": took,
            "model": config.OPENAI_REASONING_MODEL}


def look(question: str, session_key: str = "default") -> dict:
    """RIO's eyes: the existing visual pipeline, called from a live session.

    Nothing new is built here. `visual_qa.answer()` is the same path the
    hold-to-talk turn uses — the frame ring, the frame selector, reference
    resolution against tracked objects, the crop, the multimodal turn — and it
    already knows how to say "which one do you mean?" and how to refuse when
    the crop cannot carry the claim being asked for. This wires a tool call to
    it and hands the text back for RIO to speak.

    Imported lazily on purpose: the visual stack pulls in the frame ring, the
    scene tracker and the enrichment cache, and a drive where nobody asks about
    the road should not pay for any of it.

    THE ROUTE OVERRIDE. The visual path classifies the question itself, which
    is what keeps "the black one" working across turns. But the model has
    already decided this question is about what is out there — that is what
    calling `look` MEANS — so a classifier reading it as non-visual is
    overruled here rather than producing an answer with no picture behind it.
    """
    q = (question or "").strip()
    if not q:
        return {"ok": False, "note": "no question"}
    t0 = time.time()
    try:
        import router as request_router
        import visual_qa

        session = visual_qa.get_session(session_key)
        route = request_router.classify(
            q,
            has_referent=session.active_referent() is not None,
            pending_clarification=session.pending_clarification() is not None)
        if not request_router.is_visual(route["request_type"]):
            route = dict(route, request_type=request_router.SCENE,
                         requires_full_frame=True, requires_object_crop=False,
                         method="forced_by_look_tool")
        va = visual_qa.answer(session_key, q, route)
        text = (va.text() or "").strip()
    except Exception as e:
        took = round((time.time() - t0) * 1000, 1)
        print(f"[realtime] look failed after {took} ms: "
              f"{type(e).__name__}: {e}", flush=True)
        return {"ok": False, "note": f"{type(e).__name__}", "took_ms": took}

    took = round((time.time() - t0) * 1000, 1)
    if not text:
        # No frames in the ring is the ordinary version of this: the drive has
        # not started, or the camera is not running. RIO says she cannot see
        # rather than describing a road she has not been shown.
        return {"ok": False, "note": "nothing to see", "took_ms": took}
    return {"ok": True, "answer": text, "took_ms": took,
            "meta": getattr(va, "meta", None)}


def vehicle_status() -> dict:
    """How the car is — from the builder the conversation path already uses.

    `vehicle_health.context(full=True)` is not a summary written for this tool.
    It is the SAME normalised structure that goes into an ordinary
    conversation turn when the router decides a question is about the car
    (llm_interface._health_block), which is what keeps a live answer and a
    hold-to-talk answer from disagreeing about the same tire.

    It carries its own provenance — every issue says who reported it, the
    vehicle's own computer or RIO — and its own limits, including how far back
    the data actually goes. Both survive into the tool result untouched,
    because a model that is handed "26 PSI" with no history and no source will
    happily supply both.
    """
    t0 = time.time()
    try:
        import vehicle_health

        ctx = vehicle_health.context(full=True)
    except Exception as e:
        print(f"[realtime] vehicle_status failed: {type(e).__name__}: {e}", flush=True)
        return {"ok": False, "note": f"{type(e).__name__}"}
    body = ctx.get("vehicle_health", ctx)
    if not body.get("data_available", True) and not body.get("issues"):
        # Nothing is reporting. That is an answer, and a specific one: RIO says
        # she is not getting data rather than that the car is fine.
        return {"ok": True, "vehicle": body, "took_ms": round((time.time() - t0) * 1000, 1),
                "note": "no subsystem is reporting — say that, do not say the car is fine"}
    return {"ok": True, "vehicle": body,
            "took_ms": round((time.time() - t0) * 1000, 1),
            "rules": ("Only claims this data supports. Keep who reported what. "
                      "A code detected but not confirmed stays not confirmed.")}


def run_tool(name: str, arguments, session_key: str = "default") -> dict:
    """Dispatch one tool call from the live session.

    An unknown tool name is answered, not raised: the session is a model and a
    model can produce a name that is not in its own tool list. `ok: false` is a
    thing RIO already knows how to handle, and a 500 is not.
    """
    if name == VEHICLE_TOOL_NAME:
        return vehicle_status()
    if name == NAV_TOOL_NAME:
        # Answered in the BROWSER, where the route tracker lives — the server
        # holds the route but not the progress along it, and inventing a second
        # source for "how far to the next turn" is how two answers to one
        # question happen. See rio_realtime.js: local tools.
        return {"ok": False, "note": "nav_status is answered by the panel"}
    if name == NAVIGATE_TOOL_NAME:
        # Also the browser, and for a stronger reason than nav_status: this
        # one is not a read. The server can resolve a destination — it does,
        # at /nav/destination, which is what the panel calls — but it cannot
        # make the car navigate to it, because the route is loaded and tracked
        # in the page. A second implementation here could only resolve and
        # hope, which is the arrangement this tool exists to end.
        return {"ok": False, "note": "start_navigation is answered by the panel"}
    if name not in (TOOL_NAME, LOOK_TOOL_NAME):
        return {"ok": False, "note": "unknown tool"}
    if isinstance(arguments, str):
        try:
            arguments = json.loads(arguments or "{}")
        except json.JSONDecodeError:
            return {"ok": False, "note": "unreadable arguments"}
    if not isinstance(arguments, dict):
        return {"ok": False, "note": "unreadable arguments"}
    if name == LOOK_TOOL_NAME:
        return look(str(arguments.get("question") or ""), session_key)
    return escalate(str(arguments.get("question") or ""),
                    str(arguments.get("context") or ""))


def status() -> dict:
    """What the panel and /health need to know, without calling anything."""
    return {
        "enabled": bool(config.REALTIME_ENABLED),
        "model": config.OPENAI_REALTIME_MODEL,
        "voice": config.OPENAI_REALTIME_VOICE,
        "reasoning_model": config.OPENAI_REASONING_MODEL,
        "tools": [TOOL_NAME, LOOK_TOOL_NAME, NAV_TOOL_NAME, VEHICLE_TOOL_NAME,
                  NAVIGATE_TOOL_NAME],
        "web_search": bool(config.REALTIME_WEB_SEARCH),
        "tool_timeout_s": float(config.REALTIME_TOOL_TIMEOUT_S),
        "key_present": bool(os.getenv("OPENAI_API_KEY", "").strip()),
    }
