"""RIO live: one speech-to-speech session, and one tool she can reach for.

WHAT CHANGED, AND WHAT DID NOT
------------------------------
The conversation path used to be three models in a line — Whisper heard the
driver, a chat model thought, ElevenLabs spoke — and every turn paid all three
latencies in series, with a push-to-talk button holding the whole thing
together. The realtime model is all three at once: the driver's audio goes in,
RIO's audio comes out, and either of them can interrupt the other mid-word.

What did NOT change is everything that speaks deterministically. Headway
warnings, vehicle-health announcements and navigation instructions are
generated by policy code, spoken from fixed tables, and arbitrated exactly as
before. No model is anywhere near them, and this file must never become a way
in. RIO's live voice is conversation, and conversation is the tier that yields.

THE ESCALATION
--------------
Some questions want more than a fast conversational model should attempt: what
is actually open at this hour, what a fault code really means, anything needing
the web or a chain of reasoning. For those the realtime session calls ONE tool,
which asks the reasoning model and hands back text.

The driver never learns any of this happened. There is no second voice, no
"let me ask my research model" — RIO says something while it runs, then speaks
the answer as her own. And if it fails, times out, or is switched off, she
carries on and answers from what she already has: the tool returning
`ok: false` is an ordinary outcome the instructions tell her how to handle,
not an error the driver hears about.
"""
import json
import os
import threading
import time
from typing import Optional

from openai import OpenAI

import config

_client: Optional[OpenAI] = None
_client_lock = threading.Lock()

# The one tool the live session can call. Named for what the DRIVER would call
# it, not for the model behind it — nothing in the session's vocabulary should
# make a second model visible.
TOOL_NAME = "deep_dive"

TOOL_SCHEMA = {
    "type": "function",
    "name": TOOL_NAME,
    "description": (
        "Think harder about something, or look it up. Use this when the driver "
        "asks something that needs current information (opening hours, prices, "
        "news, anything that changes), specific factual research, or careful "
        "multi-step reasoning you cannot do well in a couple of seconds. Do NOT "
        "use it for chat, for anything about the car's own sensors, or for "
        "anything about the route — those are already answered elsewhere. Say a "
        "short natural line to the driver before calling it, because it takes a "
        "few seconds."
    ),
    "parameters": {
        "type": "object",
        "properties": {
            "question": {
                "type": "string",
                "description": "The question to work on, written out in full.",
            },
            "context": {
                "type": "string",
                "description": (
                    "Anything from the conversation needed to make sense of it "
                    "— what the driver actually meant, what was already said."
                ),
            },
        },
        "required": ["question"],
        "additionalProperties": False,
    },
}

# Appended to RIO's own personality prompt. Only the things that are true of a
# LIVE session and not of the text path: how to be interrupted, how long to
# talk for, and when to reach for the tool.
LIVE_ADDENDUM = """
YOU ARE LIVE, IN A MOVING CAR.

You are speaking out loud, in real time, to someone who is driving. Everything
in your character stays exactly as it is; these are the things that are only
true when you are being heard rather than read:

- Be brief by default. One or two sentences. The driver can always ask for
  more, and while you are talking they cannot hear the road.
- Expect to be interrupted, and stop cleanly when you are. Do not restate what
  you had already said — pick up from what they just asked.
- Other voices will cut you off mid-sentence: a gap warning, a tire fault, a
  turn instruction. That is correct and it is not your business. Do not
  apologise for it, do not fight it, do not repeat yourself afterwards unless
  the driver asks.
- Never give navigation instructions. You do not know the route, the next
  maneuver, or how far away it is; the navigation system does and it will say
  so itself. If the driver asks where to turn, tell them the navigation will
  call it.
- Never invent anything about the car's sensors, tires, engine, or what the
  camera can see. If you have not been told it in this conversation, you do not
  know it.
- Numbers are spoken, not written: "twenty-nine P S I", not "29 PSI".

WHEN A QUESTION NEEDS MORE THAN A QUICK ANSWER

Use the deep_dive tool. Say something natural first — "let me check", "give me
a second" — then answer in your own voice when it comes back. Never mention the
tool, and never suggest that anything other than you answered.

If it comes back with ok: false, do not mention that either. Just answer as
well as you can from what you already know, or say plainly that you cannot find
that out right now.
"""


def client() -> OpenAI:
    global _client
    with _client_lock:
        if _client is None:
            _client = OpenAI()
        return _client


def instructions() -> str:
    """RIO's personality, plus what is only true when she is being heard."""
    return (config.SYSTEM_PROMPT or "").rstrip() + "\n\n" + LIVE_ADDENDUM.strip()


def session_config() -> dict:
    """The live session, as the API wants it.

    Two choices worth stating:

    `turn_detection` is server VAD with interruption ON. That is barge-in: the
    driver starts talking, the model stops, immediately, without waiting for a
    button. In a car that is not a nicety — it is how you stop a machine that
    is mid-paragraph when you need to say something.

    `transcription` names the SAME Whisper model the rest of the system uses.
    The live session does not need a transcript to work, but the session log,
    /last_talk and every review of a drive do, and having them come from a
    different model than every other transcript in the JSONL would be a quiet
    way to make two records that disagree.
    """
    return {
        "type": "realtime",
        "model": config.OPENAI_REALTIME_MODEL,
        "instructions": instructions(),
        "audio": {
            "input": {
                "transcription": {"model": config.OPENAI_STT_MODEL},
                "turn_detection": {
                    "type": "server_vad",
                    "create_response": True,
                    "interrupt_response": True,
                },
            },
            "output": {"voice": config.OPENAI_REALTIME_VOICE},
        },
        "tools": [TOOL_SCHEMA],
        "tool_choice": "auto",
    }


def mint_client_secret() -> dict:
    """An ephemeral key for the browser, and nothing else.

    The browser needs credentials to open a WebRTC connection to the model, and
    the account key is not a thing to hand it. This mints a short-lived secret
    scoped to one session, which is the same discipline every other key on this
    page follows: routing, geocoding and TTS all go through the server, and the
    one key a browser is allowed to see is the Maps render key, which cannot do
    anything but draw a map.
    """
    secret = client().realtime.client_secrets.create(session=session_config())
    data = secret.model_dump()
    return {
        "client_secret": data.get("value"),
        "expires_at": data.get("expires_at"),
        "model": config.OPENAI_REALTIME_MODEL,
        "voice": config.OPENAI_REALTIME_VOICE,
        "tool": TOOL_NAME,
    }


def escalate(question: str, context: str = "", timeout_s: Optional[float] = None) -> dict:
    """The deep_dive tool: ask the reasoning model, hand back text.

    Never raises. Every failure — a timeout, an outage, a refusal, a model id
    that is not on this account — returns `ok: false` with a short note, and the
    session's instructions tell RIO what to do with that: carry on. A driver
    should never be able to tell the difference between "the reasoning model was
    unavailable" and "RIO decided to answer this one herself".

    The result is text for RIO to speak in her own words, so it is asked for as
    speech: no markdown, no lists, no citations read aloud like a bibliography.
    """
    q = (question or "").strip()
    if not q:
        return {"ok": False, "note": "no question"}
    timeout = float(config.REALTIME_TOOL_TIMEOUT_S if timeout_s is None else timeout_s)

    prompt = q if not context else f"{q}\n\nContext from the conversation: {context}"
    tools = [{"type": "web_search"}] if config.REALTIME_WEB_SEARCH else []
    t0 = time.time()
    try:
        # `with_options` rather than a thread: the SDK's own timeout aborts the
        # request, where a thread would leave it running and still billed.
        resp = client().with_options(timeout=timeout).responses.create(
            model=config.OPENAI_REASONING_MODEL,
            instructions=(
                "You are the research and reasoning step behind a car "
                "assistant's spoken answer. Answer the question directly and "
                "completely, in plain prose meant to be READ ALOUD: no "
                "markdown, no bullet points, no headings, no URLs, no "
                "citations. Two or three sentences unless the question genuinely "
                "needs more. If the answer depends on something you cannot "
                "verify, say so in the answer itself rather than hedging around "
                "it."
            ),
            input=prompt,
            tools=tools,
            max_output_tokens=int(config.REALTIME_TOOL_MAX_OUTPUT_TOKENS),
        )
    except Exception as e:
        took = round((time.time() - t0) * 1000, 1)
        print(f"[realtime] deep_dive failed after {took} ms: "
              f"{type(e).__name__}: {e}", flush=True)
        return {"ok": False, "note": f"{type(e).__name__}", "took_ms": took}

    text = (getattr(resp, "output_text", "") or "").strip()
    took = round((time.time() - t0) * 1000, 1)
    if not text:
        return {"ok": False, "note": "empty answer", "took_ms": took}
    return {"ok": True, "answer": text, "took_ms": took,
            "model": config.OPENAI_REASONING_MODEL}


def run_tool(name: str, arguments) -> dict:
    """Dispatch one tool call from the live session.

    An unknown tool name is answered, not raised: the session is a model and a
    model can produce a name that is not in its own tool list. `ok: false` is a
    thing RIO already knows how to handle, and a 500 is not.
    """
    if name != TOOL_NAME:
        return {"ok": False, "note": "unknown tool"}
    if isinstance(arguments, str):
        try:
            arguments = json.loads(arguments or "{}")
        except json.JSONDecodeError:
            return {"ok": False, "note": "unreadable arguments"}
    if not isinstance(arguments, dict):
        return {"ok": False, "note": "unreadable arguments"}
    return escalate(str(arguments.get("question") or ""),
                    str(arguments.get("context") or ""))


def status() -> dict:
    """What the panel and /health need to know, without calling anything."""
    return {
        "enabled": bool(config.REALTIME_ENABLED),
        "model": config.OPENAI_REALTIME_MODEL,
        "voice": config.OPENAI_REALTIME_VOICE,
        "reasoning_model": config.OPENAI_REASONING_MODEL,
        "web_search": bool(config.REALTIME_WEB_SEARCH),
        "tool_timeout_s": float(config.REALTIME_TOOL_TIMEOUT_S),
        "key_present": bool(os.getenv("OPENAI_API_KEY", "").strip()),
    }
