"""RIO live: one speech-to-speech session, and the things she can reach for.

WHAT CHANGED, AND WHAT DID NOT
------------------------------
The conversation path used to be three models in a line — Whisper heard the
driver, a chat model thought, ElevenLabs spoke — and every turn paid all three
latencies in series, with a push-to-talk button holding the whole thing
together. The realtime model is all three at once: the driver's audio goes in,
RIO's audio comes out, and either of them can interrupt the other mid-word.

What did NOT change is everything that speaks deterministically. Headway
warnings, vehicle-health announcements and navigation instructions are
generated by policy code, spoken from fixed tables, and arbitrated exactly as
before. No model is anywhere near them, and this file must never become a way
in. RIO's live voice is conversation, and conversation is the tier that yields.

THE ESCALATION
--------------
Some questions want more than a fast conversational model should attempt: what
is actually open at this hour, what a fault code really means, anything needing
the web or a chain of reasoning. For those the realtime session calls ONE tool,
which asks the reasoning model and hands back text.

The driver never learns any of this happened. There is no second voice, no
"let me ask my research model" — RIO says something while it runs, then speaks
the answer as her own. And if it fails, times out, or is switched off, she
carries on and answers from what she already has: the tool returning
`ok: false` is an ordinary outcome the instructions tell her how to handle,
not an error the driver hears about.

AND ONE THING SHE DOES
----------------------
The rest of her tools are reads: the camera, the route, the car, the reasoning
model. `start_navigation` is not. Asked to be taken somewhere, RIO sets the
destination herself, through the same path the dashboard's destination box
uses, and confirms it — where she used to describe the route and tell the
driver to set it themselves.

That is not a crack in the rule above. Announcing is speaking unasked;
routing is doing what was asked. The turns are the part that does not move:
navigation calls those, out loud, from its own tables, and nothing here may
become a way in.
"""
import json
import os
import re
import threading
import time
from typing import Optional

from openai import OpenAI

import config
import voice_tags
# Place search lives in its own module for the same reason visual_qa does: it is
# a pipeline with a bill and a licence attached, not a branch of this file.
import places

_client: Optional[OpenAI] = None
_client_lock = threading.Lock()

# The one tool the live session can call. Named for what the DRIVER would call
# it, not for the model behind it — nothing in the session's vocabulary should
# make a second model visible.
TOOL_NAME = "deep_dive"

# The second tool: RIO's eyes. The camera pipeline already exists and already
# answers questions about what is out of the window (docs/visual_qa.md) — it
# picks the clearest recent frame, resolves "the black one" to a tracked
# object, crops it and asks a multimodal model. None of that is reachable from
# a live audio session unless the session can ask for it, and a RIO who answers
# "what's that car?" from a conversational prior instead of from the camera is
# worse than one who says she cannot see it.
LOOK_TOOL_NAME = "look"

# The other two things a driver asks about that RIO cannot answer from a
# conversation prior: where we are going, and how the car is. Both already have
# a source of truth in this system and neither of them is the model.
NAV_TOOL_NAME = "nav_status"

# ...and the rest of the route, which is a different question from "what is the
# next turn" and had no tool to answer it. Asked for the directions, RIO said
# she could not read them -- correctly, given what she had: nav_status returns
# ONE maneuver, because that is what an announcement needs, and the list was in
# the browser's tracker with nothing exposing it. Reading it out when the driver
# asks is answering, which she is for, and it does not touch the boundary that
# matters: she still never CALLS a turn, because that is the arbiter's job and
# it is done at the junction, not on request.
NAV_DIRECTIONS_TOOL_NAME = "nav_directions"

# What is actually around the car. A model asked "what's good near here" will
# answer -- fluently, confidently, from a world that was current when its
# weights were made. Places that have closed, prices that moved, hours that were
# never true. The driver then drives there. So place questions leave the model
# entirely and go to Google Places, and the model's job is to say the answer
# well rather than to know it. Server-side, because the key stays here.
PLACES_TOOL_NAME = "find_places"

VEHICLE_TOOL_NAME = "vehicle_status"

# ...and the one thing on this list she DOES rather than reports. A driver who
# says "take me to the Getty" has not asked for information about the Getty;
# they have asked to be taken there, and until this existed the only honest
# thing RIO could do with that was describe the place and tell them to type it
# into the panel themselves. Setting a destination was already a solved problem
# on this page — the box resolves it, loads the route and starts the tracker —
# and this is that same path with RIO's voice as the caller. It is answered in
# the browser, where the route and the tracker live.
NAVIGATE_TOOL_NAME = "start_navigation"

TOOL_SCHEMA = {
    "type": "function",
    "name": TOOL_NAME,
    "description": (
        "Think harder about something, or look it up. Use this when the driver "
        "asks something that needs current information (news, background, "
        "anything that changes), specific factual research, or careful "
        "multi-step reasoning you cannot do well in a couple of seconds. Do NOT "
        "use it for chat, for anything about the car's own sensors, for "
        "anything about the route, or for finding a place near the car — those "
        "are already answered elsewhere, and a restaurant, a petrol station or "
        "a shop is find_places, which is one quick call to live data. Never "
        "use it for anything you can SEE either — the road, a car, a sign, a "
        "building — that is the look tool and the camera, and this one has no "
        "picture to answer from. Say a "
        "short natural line to the driver before calling it, because it takes a "
        "few seconds."
    ),
    "parameters": {
        "type": "object",
        "properties": {
            "question": {
                "type": "string",
                "description": "The question to work on, written out in full.",
            },
            "context": {
                "type": "string",
                "description": (
                    "Anything from the conversation needed to make sense of it "
                    "— what the driver actually meant, what was already said."
                ),
            },
        },
        "required": ["question"],
        "additionalProperties": False,
    },
}

LOOK_SCHEMA = {
    "type": "function",
    "name": LOOK_TOOL_NAME,
    "description": (
        "Look through the car's forward camera and answer a question about what "
        "is actually out there right now. Use this for ANY question about the "
        "road, other vehicles, signs, buildings or surroundings — 'what's that "
        "car', 'what does that sign say', 'what colour is the one on the left', "
        "'what do you see'. You cannot see anything without calling this: if a "
        "question is about the world outside the car, call it rather than "
        "guessing.\n"
        "Call it straight away, with nothing said in front of it. A general "
        "question about the road comes back instantly — the camera is already "
        "being watched — and only a question about one particular thing takes "
        "a couple of seconds."
    ),
    "parameters": {
        "type": "object",
        "properties": {
            "question": {
                "type": "string",
                "description": (
                    "The driver's question about what is visible, in their own "
                    "words as far as possible — the camera pipeline resolves "
                    "phrases like 'the black one on the left' itself."
                ),
            },
        },
        "required": ["question"],
        "additionalProperties": False,
    },
}

NAV_SCHEMA = {
    "type": "function",
    "name": NAV_TOOL_NAME,
    "description": (
        "Where the drive currently stands: destination, ETA, the next maneuver "
        "and how far away it is, whether we are on route, and whether GPS is "
        "healthy. Call this for ANY question about the route — where are we "
        "going, how long left, what's the next turn, are we lost, did we miss "
        "it. You do not otherwise know any of this. It returns instantly.\n"
        "This is for ANSWERING questions. It is not a cue to announce the turn: "
        "the navigation system calls turns itself, out loud, and you must not."
    ),
    "parameters": {"type": "object", "properties": {}, "additionalProperties": False},
}

NAV_DIRECTIONS_SCHEMA = {
    "type": "function",
    "name": NAV_DIRECTIONS_TOOL_NAME,
    "description": (
        "The turn-by-turn directions for the route we are on: the upcoming "
        "maneuvers in order, each with the instruction, the road, how far away "
        "it is and which way it turns. Call this whenever the driver asks for "
        "the directions, the route, 'what are the turns', 'what's after that', "
        "'read me the directions', 'how do we get there' — anything that wants "
        "more than the single next maneuver nav_status returns. Returns the "
        "next five by default; pass a count, or \"all\" for the whole route.\n"
        "Reading these out because you were asked is ANSWERING and it is what "
        "this tool is for. It is still not a cue to call a turn: each one is "
        "announced by the navigation system at the moment it happens, and that "
        "is not yours. Some maneuvers come with a landmark the map expects to "
        "be there — say so as an expectation ('there should be a Shell'), "
        "never as something you can see."
    ),
    "parameters": {
        "type": "object",
        "properties": {
            "count": {
                "type": "string",
                "description": (
                    "How many upcoming maneuvers to return: a number as text "
                    "(\"3\"), or \"all\" for the whole remaining route. "
                    "Omit for the next five."
                ),
            },
        },
        "required": [],
        "additionalProperties": False,
    },
}

PLACES_SCHEMA = {
    "type": "function",
    "name": PLACES_TOOL_NAME,
    "description": (
        "Find real businesses and places around the car: restaurants, coffee, "
        "petrol, parking, shops, anything with an address. Call this for ANY "
        "question about places — 'what's good round here', 'where's the nearest "
        "petrol', 'find me a coffee', 'is there parking near the beach', 'is "
        "the Blue Bottle on Main open'. It returns live Google Places data: "
        "name, rating and how many reviews, price, whether it is open now, how "
        "far away it is and roughly how long to drive there.\n"
        "You do NOT know any of this yourself. Anything you remember about a "
        "restaurant is from when you were trained — it may have closed, moved "
        "or changed hands, and the driver will act on what you say. So never "
        "answer a place question from memory, and never use the research tool "
        "for one: this is the tool for it, and if it comes back empty or fails "
        "you say you could not pull it up rather than filling the gap."
    ),
    "parameters": {
        "type": "object",
        "properties": {
            "query": {
                "type": "string",
                "description": (
                    "What to look for, in ordinary words: 'coffee', 'tacos', "
                    "'petrol station', 'Blue Bottle Coffee', 'parking'."
                ),
            },
            "near": {
                "type": "string",
                "description": (
                    "An area, ONLY if the driver named one ('Santa Monica', "
                    "'downtown', 'near the pier'). Leave it out for 'near me', "
                    "'round here' or no area at all — the car's own position is "
                    "used then."
                ),
            },
            "open_now": {
                "type": "boolean",
                "description": (
                    "True when they want somewhere open right now — 'open', "
                    "'still open', 'open right now'. Leave it out otherwise."
                ),
            },
            "count": {
                "type": "integer",
                "description": "How many results to fetch. Omit for five.",
            },
        },
        "required": ["query"],
        "additionalProperties": False,
    },
}

VEHICLE_SCHEMA = {
    "type": "function",
    "name": VEHICLE_TOOL_NAME,
    "description": (
        "How the car itself is: live sensor summary, anything the vehicle's "
        "computer has reported, anything RIO has observed, and any fault codes "
        "including ones detected but not yet confirmed. Call this for ANY "
        "question about the car — the tires, the engine, oil, coolant, the "
        "battery, warning lights, 'is everything okay', 'is anything wrong'. "
        "You do not otherwise know any of it, and you must never guess at a "
        "number. It returns instantly.\n"
        "This is for ANSWERING questions. Health announcements are made by the "
        "car itself; you do not make them."
    ),
    "parameters": {"type": "object", "properties": {}, "additionalProperties": False},
}

NAVIGATE_SCHEMA = {
    "type": "function",
    "name": NAVIGATE_TOOL_NAME,
    "description": (
        "Start navigating somewhere. This is how the driver actually gets "
        "taken to a place: 'take me to the Getty', 'navigate to LAX', "
        "'let's go to Ralphs', 'directions to 1200 Getty Center Drive'. It "
        "resolves the destination and makes the route live — the same thing "
        "that happens when a destination is typed into the panel — so you "
        "never tell the driver to set it themselves. Call it as soon as they "
        "ask; do not ask permission first.\n"
        "If the driver is choosing one of the places find_places just gave "
        "you, pass that result's place_id as well as its name — it is already "
        "resolved.\n"
        "It can come back asking WHICH ONE: more than one place answers to "
        "what they said. Put that question to the driver in your own words and "
        "call this again with their answer. Never pick one yourself.\n"
        "Setting the route does not make you the voice of the turns. The "
        "navigation system still calls those out loud itself, and you still "
        "must not."
    ),
    "parameters": {
        "type": "object",
        "properties": {
            "destination": {
                "type": "string",
                "description": (
                    "The place the driver asked for, in their own words. "
                    "Leading phrases like 'take me to' are stripped for you, "
                    "so the sentence as they said it is fine. If they have "
                    "just chosen between places you offered, pass the full "
                    "name of the one they chose."
                ),
            },
            "place_id": {
                "type": "string",
                "description": (
                    "The place_id from a find_places result, when the driver "
                    "picked one of the places you just read out ('the second "
                    "one', 'the Blue Bottle'). Pass it WITH the name: it is the "
                    "exact place, already resolved, so nothing has to be looked "
                    "up again and there is no chance of routing to a different "
                    "branch of the same chain. Leave it out for anywhere else."
                ),
            },
        },
        "required": ["destination"],
        "additionalProperties": False,
    },
}

# Appended to RIO's own personality prompt. Only the things that are true of a
# LIVE session and not of the text path: how to be interrupted, how long to
# talk for, and when to reach for the tool.
LIVE_ADDENDUM = """
YOU ARE LIVE, IN A MOVING CAR.

You are speaking out loud, in real time, to someone who is driving. Everything
in your character stays exactly as it is; these are the things that are only
true when you are being heard rather than read:

- Be brief by default. One or two sentences. The driver can always ask for
  more, and while you are talking they cannot hear the road. A first answer is
  ALWAYS short — depth is something they ask for, never something you decide
  they wanted.
- Expect to be interrupted, and stop cleanly when you are. Do not restate what
  you had already said — pick up from what they just asked.
- Other voices will cut you off mid-sentence: a gap warning, a tire fault, a
  turn instruction. That is correct and it is not your business. Do not
  apologise for it, do not fight it, do not repeat yourself afterwards unless
  the driver asks.
YOU ANSWER. YOU DO NOT ANNOUNCE.

This is the line that matters most, and it is not about tone — it is about two
voices saying the same thing at once. The car announces things on its own:
turn instructions, health warnings, hazard alerts. Those come from the car's own
systems, in your voice, and they are already handled.

So: never announce a turn, a fault, or a hazard on your own initiative. Not
when a tool result shows one. Not when you think it would be helpful. If
nav_status tells you a turn is coming in four seconds, that is CONTEXT for
answering the driver — it is not a cue to say "turn left here", because the
navigation system is about to say exactly that and you would be talking over
it.

Asked, you answer freely: "where are we going", "how far", "what's the next
turn", "read me the directions", "is everything okay with the car".
Unasked, you say nothing about any of it.

Reading the directions when the driver asks for them is ANSWERING, and it is
not the thing this rule is about. The rule is about CALLING a turn — saying
"left here" at the junction, over the driver, because a tool result mentioned
it. That call belongs to the navigation system and is made at the moment it is
useful. A driver asking "what are the turns?" three miles earlier is asking a
question, and a question gets an answer.

Being asked to DO something is not an exception to this, it is the other half
of it. "Take me to the Getty" is not an announcement waiting to happen, it is
an instruction, and carrying it out is answering. So you start routes. What you
still never do is call the turns along the way.

- Never invent anything about the car, the route, or the road. You have tools
  for all three and they are the only way you know any of it — including
  setting a destination, which is a tool and not something you can ask the
  driver to do for you.
- You cannot see. The camera is a tool — `look` — and it is the only way you
  know what is out of the window. Anything about the road, another vehicle, a
  sign, a building or the surroundings goes through it, every time, even when
  you think you can guess from what was said a moment ago. A confident answer
  about a car you did not look at is the worst thing you can do here.
- Numbers are spoken, not written: "twenty-nine P S I", not "29 PSI".

WHEN THE DRIVER ASKS ABOUT SOMETHING OUTSIDE THE CAR

TWO TIERS, AND THE FIRST ONE IS ALWAYS SHORT.

The first answer to anything you can see is the camera's, and it is one or two
sentences. "What's that building?" — say what it is. "What car is that?" — say
what it is. That is the whole answer. The driver is driving; they asked a
question, not for a briefing, and several seconds of silence followed by a
paragraph is the worst thing you can do to somebody at the wheel.

So: use the look tool. Never use the research tool for anything you can see —
it has no picture, and a description of a road it cannot look at is invention
with a delay in front of it. It will refuse a first look anyway, and tell you
to answer from what you already have.

THEN OFFER, DON'T DELIVER. When the thing is worth more — a landmark, a named
building, something unusual — add one short clause at the end: "want to know
more about it?" One clause, not a paragraph, and not every time: an ordinary
car in ordinary traffic has nothing to offer and asking about it is noise.

ONLY WHEN THEY ASK. "Tell me more", "what's the history", or just "yes" after
you offered — then use the research tool. Say a holding line first, because
that one does take a few seconds. Keep the answer to three or four sentences
and offer to go on rather than going on.

CALL IT FIRST AND SAY NOTHING IN FRONT OF IT. Not "let me look", not "one
second" — call the tool, wait, then answer. A plain "what do you see" comes
back in about four milliseconds, because the camera is already being watched
and the answer was ready before the driver finished asking; a holding line in
front of that is not politeness, it is the only slow part of the turn. Every
word you say before the call is a word you compose before the camera has even
been asked, and the driver waits through all of it.

The rare slow one — a question about a particular thing, which has to crop the
frame and look properly — takes a couple of seconds, and a couple of seconds of
silence is what a passenger does when they turn their head to look. Silence is
a tone here, not a gap to fill.

What comes back is short factual background: describe it in your own words, as
you would anything else. Answer with what it gives you and nothing more; if it
says it cannot see, or asks which one the driver meant, say that, in your own
words.

WHEN THE DRIVER ASKS TO GO SOMEWHERE

"Take me to the Getty." "Navigate to LAX." "Let's go get coffee at the Ralphs
on Lincoln." Call start_navigation, straight away. It sets the destination and
starts the route — the same route the panel would have loaded — and it is
YOURS. Never tell the driver to type it in, to set it on the screen, or to do
anything about it themselves. That was the old arrangement and it was a bad
one: you were describing a drive you would not begin.

Then say one short line confirming it, in your own words: "Getting you to the
Getty — about eighteen minutes." Two rules about that line and nothing else is
prescribed: use the destination name the tool hands back, spelled its way
rather than the way you heard it — LAX and LAS are one letter apart and only
one of them is where they are going — and say it once.

The tool hands you the route itself as well — how many turns, and the first few
spelled out — so you can confirm from that without asking anything else. Do not
read them out as part of the confirmation; one line is the confirmation. If the
driver then asks what the turns are, that is nav_directions and it is answering.

If it comes back asking WHICH ONE, it has found more than one place that
answers to what they said, and choosing between them is not yours to do. Ask —
name them, briefly — and when the driver answers, call start_navigation again
with what they chose. If it could not find the place at all, say so and ask
them to put it another way. If the route itself failed, say that plainly too.
None of those three are cues to hand the job back to the driver.

WHEN THE DRIVER ASKS FOR THE DIRECTIONS

"What are the directions?" "What are the turns?" "How do we get there?" "What's
after Lincoln?" Call nav_directions and read what comes back — that is what it
is for, and refusing to read a route you are driving is not a boundary, it is a
gap.

Say it the way a person gives directions, not the way a screen lists them. One
flowing line or two: "First a right onto Lincoln in about half a mile, then
left on Sunset, then it's straight for six miles." Round the distances — "about
half a mile", "a couple of miles" — because nobody says four hundred and twenty
metres. Name the roads exactly as the tool spells them. Stop after the first
few unless they asked for all of it, and offer the rest rather than reciting
it.

Some turns come back with a landmark. Say it as an EXPECTATION, because that is
what it is: the map found a petrol station near that junction and nobody has
looked at it yet. "Then a left onto Sunset — there should be a Shell on the
corner." Never "there's a Shell", never "you'll see a Shell". If a landmark is
really there, the car says so at the turn, once it has actually seen it.

And it stays an answer. You are reading a route, not calling it: no "turn left
here", no "get ready to turn", nothing that sounds like an instruction for
right now. Each of those turns gets called by the navigation system when it
arrives.

WHEN THE DRIVER ASKS ABOUT THE ROUTE, OR ABOUT THE CAR

Use nav_status or vehicle_status. Both are instant, so just call them — no
holding line needed. Never answer either kind of question from memory or from
what you were told earlier in the drive: the whole point of them is that the
answer changes while you are talking.

Answering about the car, three rules that are not negotiable:
  * Say only what the data supports. If a field is not there, you do not know
    it. No estimated pressures, no invented mileage, no "probably fine".
  * Keep the provenance. Something the vehicle's own computer reported and
    something RIO noticed are different claims and must sound different.
  * A code that is detected but NOT CONFIRMED is exactly that. Say it that way —
    "the car has picked something up but hasn't confirmed it yet" — and never
    upgrade it to a fault.

WHEN THE DRIVER ASKS ABOUT A PLACE

"What's good round here." "Where's the nearest petrol." "Find me a coffee."
"Is the Blue Bottle on Main open?" "Anywhere to park near the pier?" All of
these go to find_places, every time, without exception.

You do not know any of this. What you remember about restaurants is from when
you were trained: some of those places have closed, moved, changed hands or
changed their hours, and the driver is going to DRIVE to whatever you say. A
confident wrong answer about a business is worse than no answer at all, because
they act on it. So the rule has no soft edge — never name a business, a rating,
a price or an opening time that did not come back from find_places in this
conversation. Not as a guess, not as "I think there's a", not as a suggestion
to check.

Do not use the research tool for this either. It is for questions that need
thinking or looking up in general; a place round the corner is what find_places
is, and it is one quick call.

Reading the results: the best two or three, not the list. Name it, say what
makes it worth picking — the rating, how close it is, whether it is open — and
offer the rest. "Two good ones close by: Dogtown Coffee, four point four, about
four minutes, open now. Or Blue Bottle, a bit further but rated higher. Want
the others?" The drive time is an estimate, so it is always "about".

If the search comes back with nothing, say so and offer to look for something
else or somewhere else. If it fails, say plainly that you could not pull it up
right now. Neither of those is a cue to remember a place instead.

If it says it does not know where the car is, ask which area to search — one
short question — and call it again with that area.

WHEN THEY PICK ONE

"Take me to the second one." "Let's go to the Blue Bottle." That is
start_navigation, and the result you already have carries the place_id for
every place you read out. Pass that id along with the name: it is the same
place, already resolved, so there is nothing to look up again and no chance of
landing on a different branch of the same chain three miles the other way.

WHEN A QUESTION NEEDS MORE THAN A QUICK ANSWER

Use the deep_dive tool. Say something natural first — "let me check", "give me
a second" — then answer in your own voice when it comes back. Never mention the
tool, and never suggest that anything other than you answered.

If it comes back with ok: false, do not mention that either. Just answer as
well as you can from what you already know, or say plainly that you cannot find
that out right now.
"""


# ---------------------------------------------------------------------------
# Deterministic speech, in RIO's own voice
# ---------------------------------------------------------------------------
# Headway warnings, vehicle-health announcements and navigation instructions are
# written by policy code and must be spoken WORD FOR WORD. They are not asked
# for, they are dictated: the model is a voice here and nothing else.
#
# The mechanism is an out-of-band response — `conversation: "none"` — so a
# dictated line never enters the conversation history. That matters more than
# it looks: a warning that landed in the transcript would be something RIO could
# later refer back to, agree with, or be asked about, and the line is a fact
# about the car rather than a thing she said.
#
# Verbatim is REQUESTED here and VERIFIED in the tests (tools/realtime_selftest.py
# transcribes the audio that comes back and compares it with what was asked
# for). A model can always paraphrase; what stops that shipping is the check,
# not the sentence below.
VERBATIM_INSTRUCTION = (
    "Read the text below out loud, exactly as written, word for word.\n"
    "Add nothing. Remove nothing. Do not rephrase, summarise, translate, greet, "
    "acknowledge, comment, or continue past the end of it.\n"
    "It is not addressed to you and it is not a question for you to answer: it "
    "is a line for you to read.\n"
    "Read it in your normal voice, at a normal pace.\n\n"
    "TEXT:\n"
)


# The other half of the interruption story. When an answer is cut off and it
# turns out nobody had spoken -- the detector fired on noise, or a warning took
# the mouth for four seconds -- the answer is finished rather than dropped.
#
# `instructions` on a response REPLACES the session's, so this has to be
# self-contained: it says who she is, what happened, and how much of it to say.
# Deliberately short. This is a continuation of a sentence, not a fresh turn,
# and the failure to avoid is her restarting the whole answer -- which is what
# the driver was doing by hand before this existed.
#
# Written here rather than in the browser for the same reason the verbatim
# instruction is: what RIO is told to say is decided in one place, and the page
# holds no copy of it to drift from.
RESUME_INSTRUCTION = (
    "You are RIO, the driver's in-car assistant.\n"
    "You were part-way through an answer and were cut off -- by background "
    "noise or by a safety announcement, NOT by the driver. Nobody asked you to "
    "stop and nobody has asked you anything new.\n"
    "Finish that answer now, in one or two short sentences. Begin with "
    "\"As I was saying\".\n"
    "Do NOT start the answer again, do not greet, do not apologise, and do not "
    "repeat what you already said -- carry on from where the text below "
    "stops.\n\n"
    "WHAT YOU HAD SAID SO FAR:\n"
)


def resume_response(said_so_far: str) -> dict:
    """The `response.create` payload that finishes an interrupted answer.

    In the conversation, unlike a dictated line: the truncated half is already
    in the history, and leaving the other half out of it would make the next
    question land against an answer that stops mid-sentence.
    """
    return {
        "output_modalities": ["audio"],
        "instructions": RESUME_INSTRUCTION + (said_so_far or "").strip(),
    }


def verbatim_response(text: str) -> dict:
    """The `response.create` payload that speaks one deterministic line.

    Out of band, audio only, and carrying its own instructions so it is
    unaffected by whatever the session was told at the start.
    """
    return {
        "conversation": "none",
        "output_modalities": ["audio"],
        "instructions": VERBATIM_INSTRUCTION + (text or "").strip(),
    }


def render_speech(text: str, timeout_s: float = 30.0) -> dict:
    """Speak one line through a short-lived session and return the audio.

    Server-side, synchronous, and not on any live path — this exists to
    PRE-RENDER the critical clips in the same voice the live session uses, and
    to give the tests something to transcribe. The car never calls it: in the
    car the browser already holds a session and dictates into that one.

    Returns {ok, wav, transcript, ms} — `transcript` being the model's own
    account of what it said, which is the first half of the verbatim check.
    """
    import base64
    import io
    import wave

    line = (text or "").strip()
    if not line:
        return {"ok": False, "note": "no text"}
    t0 = time.time()
    pcm = bytearray()
    transcript = ""
    try:
        with client().realtime.connect(model=config.OPENAI_REALTIME_MODEL) as conn:
            conn.session.update(session={
                "type": "realtime",
                "output_modalities": ["audio"],
                "audio": {"output": {
                    "voice": config.OPENAI_REALTIME_VOICE,
                    "format": {"type": "audio/pcm", "rate": 24000},
                }},
            })
            conn.response.create(response=verbatim_response(line))
            for event in conn:
                if event.type == "response.output_audio.delta":
                    pcm += base64.b64decode(event.delta)
                elif event.type == "response.output_audio_transcript.done":
                    transcript = event.transcript or ""
                elif event.type == "response.done":
                    break
                elif event.type == "error":
                    return {"ok": False, "note": str(getattr(event, "error", "error"))}
                if (time.time() - t0) > timeout_s:
                    return {"ok": False, "note": "timeout"}
    except Exception as e:
        print(f"[realtime] render failed: {type(e).__name__}: {e}", flush=True)
        return {"ok": False, "note": f"{type(e).__name__}"}
    if not pcm:
        return {"ok": False, "note": "no audio"}
    buf = io.BytesIO()
    with wave.open(buf, "wb") as w:
        w.setnchannels(1)
        w.setsampwidth(2)
        w.setframerate(24000)
        w.writeframes(bytes(pcm))
    return {"ok": True, "wav": buf.getvalue(), "transcript": transcript,
            "ms": round((time.time() - t0) * 1000, 1),
            "seconds": round(len(pcm) / 48000.0, 2)}


# ---------------------------------------------------------------------------
# WHY AN ANSWER STOPPED — the tally
# ---------------------------------------------------------------------------
# "Her voice keeps cutting out" is four faults wearing one coat, and the only
# way to tell which one a car is actually suffering from is to count them
# separately while somebody drives it. The browser classifies each cut-off (it
# is the only place that can: the cause is a question about audio timing and a
# transcript that never arrived) and posts it here, so a ten-turn test produces
# a number instead of an impression.
#
# In memory and per process, like the headway session registry: this is a
# diagnostic for the drive that is happening now, and the durable copy is the
# session JSONL, which sessions.log_live_cutoff writes.
_CUTOFF_CAUSES = ("false_barge_in", "barge_in", "preempted",
                  "token_cap", "transport", "other")
_cutoff_lock = threading.Lock()
_cutoffs: dict = {"tally": {c: 0 for c in _CUTOFF_CAUSES},
                  "resumed": 0, "resume_skipped": 0, "blips_absorbed": 0,
                  "recent": []}
_CUTOFF_RECENT_MAX = 50


def record_cutoff(kind: str, cause: str, detail: dict) -> dict:
    """One cut-off, one resume, or one absorbed blip, as reported by the page."""
    with _cutoff_lock:
        if kind == "cutoff":
            c = cause if cause in _CUTOFF_CAUSES else "other"
            _cutoffs["tally"][c] += 1
        elif kind in ("resumed", "resume_skipped", "blips_absorbed"):
            _cutoffs[kind] += 1
        rec = {"t": round(time.time(), 3), "kind": kind, "cause": cause}
        rec.update({k: v for k, v in (detail or {}).items()
                    if k in ("response_id", "reason", "detail", "said_chars", "by")})
        _cutoffs["recent"].append(rec)
        if len(_cutoffs["recent"]) > _CUTOFF_RECENT_MAX:
            _cutoffs["recent"] = _cutoffs["recent"][-_CUTOFF_RECENT_MAX:]
        return rec


def cutoff_tally() -> dict:
    with _cutoff_lock:
        t = dict(_cutoffs["tally"])
        return {
            "cutoffs": t,
            "cutoffs_total": sum(t.values()),
            # Barge-ins the sustain gate absorbed before they cost anything.
            # Under the old behaviour every one of these was a lost answer, so
            # this is the number that says whether the fix is doing anything.
            "blips_absorbed": _cutoffs["blips_absorbed"],
            "resumed": _cutoffs["resumed"],
            "resume_skipped": _cutoffs["resume_skipped"],
            "recent": list(_cutoffs["recent"]),
            "policy": {
                "vad_threshold": config.REALTIME_VAD_THRESHOLD,
                "vad_prefix_ms": config.REALTIME_VAD_PREFIX_MS,
                "vad_silence_ms": config.REALTIME_VAD_SILENCE_MS,
                "barge_sustain_ms": config.REALTIME_BARGE_SUSTAIN_MS,
                "barge_confirm_ms": config.REALTIME_BARGE_CONFIRM_MS,
                "max_resumes": config.REALTIME_MAX_RESUMES,
                "server_interrupt_response": False,
            },
        }


def reset_cutoffs() -> None:
    with _cutoff_lock:
        _cutoffs["tally"] = {c: 0 for c in _CUTOFF_CAUSES}
        _cutoffs["resumed"] = 0
        _cutoffs["resume_skipped"] = 0
        _cutoffs["blips_absorbed"] = 0
        _cutoffs["recent"] = []


def client() -> OpenAI:
    global _client
    with _client_lock:
        if _client is None:
            _client = OpenAI()
        return _client


def instructions() -> str:
    """RIO's personality, plus what is only true when she is being heard.

    The audio-tag paragraph is generated from the same config the VALIDATOR
    enforces (voice_tags.instruction), and only when tags are actually
    reachable — which under the cedar backend they are not. A model told it may
    do something the gate will undo is a model that keeps trying, and the
    instruction and the enforcement being two expressions of one list is what
    stops them drifting.
    """
    parts = [(config.SYSTEM_PROMPT or "").rstrip(), LIVE_ADDENDUM.strip()]
    if config.VOICE_BACKEND == "elevenlabs":
        tags = voice_tags.instruction()
        if tags:
            parts.append(tags.strip())
    return "\n\n".join(p for p in parts if p)


def session_config() -> dict:
    """The live session, as the API wants it.

    Two choices worth stating:

    `turn_detection` is server VAD, tuned for a cabin rather than a headset,
    with `interrupt_response` OFF — and that last one is the interesting choice.

    Interruption still happens, and still happens instantly. It happens in the
    BROWSER: static/rio_realtime.js mutes RIO on the first sample the detector
    calls speech, before any round trip, so she is never audible over the
    driver. What it does NOT do instantly is throw her answer away. It waits
    REALTIME_BARGE_SUSTAIN_MS to see whether the speech is still going, and
    only then cancels her generation.

    That gap is the whole point. With `interrupt_response: True` the server
    cancels on the first frame that crosses the threshold, and in a car the
    thing that crosses it is very often RIO's own voice coming back through the
    cabin, or a cough, or the indicator. The answer was gone before anything
    could ask whether a person had actually said something, and the driver had
    to ask again. Deciding it here would be deciding it 300 ms and one network
    hop away from the microphone; the browser already has the audio and the
    element to mute, so the browser decides.

    `transcription` names the SAME Whisper model the rest of the system uses.
    The live session does not need a transcript to work, but the session log,
    /last_talk and every review of a drive do, and having them come from a
    different model than every other transcript in the JSONL would be a quiet
    way to make two records that disagree.

    WHAT THE SESSION PRODUCES depends on whose voice RIO has, and it is the
    ONLY thing that does. Under the ElevenLabs backend the output is text and
    something else speaks it; under the cedar backend the output is audio and
    she speaks for herself. The INPUT half is identical either way — she is
    still listening to the cabin, still transcribing with the same Whisper,
    still deciding for herself when the driver has stopped talking — because
    the change is about her mouth and nothing about her ears.

    The voice is named even in text mode. It costs nothing, produces nothing
    while the modality is text, and means the cedar fallback is a modality
    switch rather than a modality switch plus a configuration the session has
    to be told for the first time mid-drive.
    """
    text_out = config.VOICE_BACKEND == "elevenlabs"
    return {
        "type": "realtime",
        "model": config.OPENAI_REALTIME_MODEL,
        "instructions": instructions(),
        "output_modalities": ["text"] if text_out else ["audio"],
        "audio": {
            "input": {
                "transcription": {"model": config.OPENAI_STT_MODEL},
                "turn_detection": {
                    "type": "server_vad",
                    "threshold": float(config.REALTIME_VAD_THRESHOLD),
                    "prefix_padding_ms": int(config.REALTIME_VAD_PREFIX_MS),
                    "silence_duration_ms": int(config.REALTIME_VAD_SILENCE_MS),
                    "create_response": True,
                    # See the docstring: the browser owns interruption.
                    "interrupt_response": False,
                },
            },
            "output": {"voice": config.OPENAI_REALTIME_VOICE},
        },
        "tools": [TOOL_SCHEMA, LOOK_SCHEMA, NAV_SCHEMA, NAV_DIRECTIONS_SCHEMA,
                  PLACES_SCHEMA, VEHICLE_SCHEMA, NAVIGATE_SCHEMA],
        "tool_choice": "auto",
        # A ceiling on any single spoken answer, at the API rather than in the
        # prompt. The instructions ask for brevity and mostly get it; this is
        # what makes a five-paragraph answer impossible rather than unlikely.
        # It is not a target — ordinary answers are a fraction of it — it is
        # the point past which something has gone wrong and the driver should
        # not have to sit through the rest of it.
        "max_output_tokens": int(config.REALTIME_MAX_RESPONSE_TOKENS),
    }


def mint_client_secret() -> dict:
    """An ephemeral key for the browser, and nothing else.

    The browser needs credentials to open a WebRTC connection to the model, and
    the account key is not a thing to hand it. This mints a short-lived secret
    scoped to one session, which is the same discipline every other key on this
    page follows: routing, geocoding and TTS all go through the server, and the
    one key a browser is allowed to see is the Maps render key, which cannot do
    anything but draw a map.
    """
    cfg = session_config()
    secret = client().realtime.client_secrets.create(session=cfg)
    data = secret.model_dump()
    return {
        "client_secret": data.get("value"),
        "expires_at": data.get("expires_at"),
        "model": config.OPENAI_REALTIME_MODEL,
        "voice": config.OPENAI_REALTIME_VOICE,
        "tool": TOOL_NAME,
        "tools": [t["name"] for t in cfg["tools"]],
        # Dictation policy travels WITH the session, so the browser holds no
        # copy of the verbatim instruction that could drift from this one. What
        # RIO is told to read a warning as is decided here, once.
        "verbatim_instruction": VERBATIM_INSTRUCTION,
        # WHOSE VOICE, and everything the page needs to build the mouth for it.
        # Sent with the session for the same reason the dictation and resume
        # policies are: the browser holds no second copy of a decision made in
        # config.py, so there is nothing to drift.
        "voice_backend": config.VOICE_BACKEND,
        "cedar_voice": config.OPENAI_REALTIME_VOICE,
        "voice_sample_rate": int(config.ELEVENLABS_SAMPLE_RATE),
        "output_modalities": cfg["output_modalities"],
        # ...and so does the resume policy, for the same reason: one place
        # decides what she says and how long she waits before deciding nobody
        # spoke. See rio_realtime.js createController.
        "resume_instruction": RESUME_INSTRUCTION,
        "barge_sustain_ms": int(config.REALTIME_BARGE_SUSTAIN_MS),
        "barge_confirm_ms": int(config.REALTIME_BARGE_CONFIRM_MS),
        "max_resumes": int(config.REALTIME_MAX_RESUMES),
        # DICTATION IS A PROPERTY OF THE CEDAR BACKEND.
        #
        # It exists so a warning comes out of the same mouth as a conversation,
        # and under ElevenLabs it already does: /nav/voice, /headway_voice and
        # /vehicle/health/voice synthesise on the SAME voice id, on the model
        # that is fastest to first byte. Dictating to a text-mode session would
        # produce a warning as text, spoken by the conversational model through
        # a socket built for prosody — slower, out of band, and for nothing.
        "speech_enabled": bool(config.REALTIME_SPEECH_ENABLED
                               and config.VOICE_BACKEND != "elevenlabs"),
        # How long an answer to a camera question may be. Carried with the
        # session like every other policy the page enforces, so the number
        # lives in config.py and the browser holds no copy of it.
        "look_answer_max_tokens": int(config.REALTIME_LOOK_ANSWER_MAX_TOKENS),
        "speech_channels": dict(config.REALTIME_SPEECH_CHANNELS),
        "speak_timeout_ms": int(config.REALTIME_SPEAK_TIMEOUT_MS),
    }


# ---------------------------------------------------------------------------
# TWO TIERS OF ANSWER
# ---------------------------------------------------------------------------
# The first answer to anything the camera can see is the camera's, and it is
# short. Depth is a second turn, and only if the driver asks for one.
#
# This exists because deep_dive was reachable from "what's that building?" --
# a question look() answers in a sentence -- and the driver got several seconds
# of silence followed by a paragraph. The instructions asked for the right
# behaviour and mostly got it; "mostly" is not a policy, and a rule that is
# only in a prompt is a rule the model may reconsider.
#
# So the tiers are enforced here, in the tool, where reconsidering is not
# available.

_visual_turns = {}                  # session_key -> {"last_look_t", "depth_until"}
_turns_lock = threading.Lock()

# The driver asking for more. Any of these unlocks the reasoning model for
# DEPTH_WINDOW_S, because a follow-up chain about one building is one
# conversation rather than a series of cold questions.
_DEPTH_REQUEST = re.compile(
    r"\b(tell me more|more about|more detail|say more|go on|go deeper|"
    r"elaborate|expand on|what'?s the (?:history|story)|history of|"
    r"who (?:built|designed|owns|made)|when was|how old|why (?:is|was|did)|"
    r"background on|anything else about|what else)\b",
    re.IGNORECASE)

# A question the camera should answer. Not a classifier -- the router is that,
# and it can cost a model call. This is the cheap test for "the driver is
# asking about something out of the window", used only to decide whether a
# deep_dive is jumping the queue.
_LOOKS_VISUAL = re.compile(
    r"\b(that|those|this)\s+(building|car|vehicle|truck|sign|shop|store|"
    r"place|thing|one)\b"
    r"|\bwhat(?:'?s| is| kind of| sort of)?\s+(?:that|this|the)\s+"
    r"(building|car|vehicle|truck|sign|shop|store|place|thing)\b"
    r"|\bwhat do you see\b|\bout (?:of )?the window\b"
    r"|\b(?:on|to) (?:the|our) (?:left|right)\b"
    r"|\bahead of us\b|\bin front of us\b",
    re.IGNORECASE)


def note_look(session_key: str, question: str) -> None:
    """A visual question was just answered from the camera."""
    with _turns_lock:
        st = _visual_turns.setdefault(str(session_key or "default"), {})
        st["last_look_t"] = time.time()
        st["last_look_q"] = (question or "")[:200]


def unlock_depth(session_key: str) -> None:
    """The driver asked for more. Depth is open for a while."""
    with _turns_lock:
        st = _visual_turns.setdefault(str(session_key or "default"), {})
        st["depth_until"] = time.time() + float(config.DEPTH_WINDOW_S)


def depth_allowed(session_key: str, question: str, context: str = "") -> dict:
    """May this deep_dive run? -> {"allowed", "reason"}

    Refused in exactly one situation, and it is the one that made visual
    questions slow: a question about something the camera can see, asked cold
    -- either while a look for this session is still the current exchange, or
    phrased as a question about what is out of the window -- with nothing in it
    that asks for depth.

    Everything else runs. "What's the speed limit in California", "how does
    regenerative braking work", "what time does the game start" are all cold
    questions and none of them is a first look; the reasoning model is exactly
    right for them and this gate never sees them.
    """
    text = f"{question or ''} {context or ''}"
    key = str(session_key or "default")
    now = time.time()

    if _DEPTH_REQUEST.search(text):
        unlock_depth(key)
        return {"allowed": True, "reason": "asked_for_depth"}

    with _turns_lock:
        st = dict(_visual_turns.get(key) or {})
    if st.get("depth_until", 0) > now:
        return {"allowed": True, "reason": "depth_window_open"}

    looked_recently = (now - st.get("last_look_t", 0)) < float(config.DEPTH_COLD_S)
    if looked_recently or _LOOKS_VISUAL.search(text):
        return {"allowed": False,
                "reason": "first_look" if looked_recently else "visual_question"}
    return {"allowed": True, "reason": "not_a_visual_question"}


def escalate(question: str, context: str = "", timeout_s: Optional[float] = None) -> dict:
    """The deep_dive tool: ask the reasoning model, hand back text.

    Never raises. Every failure — a timeout, an outage, a refusal, a model id
    that is not on this account — returns `ok: false` with a short note, and the
    session's instructions tell RIO what to do with that: carry on. A driver
    should never be able to tell the difference between "the reasoning model was
    unavailable" and "RIO decided to answer this one herself".

    The result is text for RIO to speak in her own words, so it is asked for as
    speech: no markdown, no lists, no citations read aloud like a bibliography.
    """
    q = (question or "").strip()
    if not q:
        return {"ok": False, "note": "no question"}
    timeout = float(config.REALTIME_TOOL_TIMEOUT_S if timeout_s is None else timeout_s)

    prompt = q if not context else f"{q}\n\nContext from the conversation: {context}"
    tools = [{"type": "web_search"}] if config.REALTIME_WEB_SEARCH else []
    t0 = time.time()
    try:
        # `with_options` rather than a thread: the SDK's own timeout aborts the
        # request, where a thread would leave it running and still billed.
        resp = client().with_options(timeout=timeout).responses.create(
            model=config.OPENAI_REASONING_MODEL,
            instructions=(
                "You are the research and reasoning step behind a car "
                "assistant's spoken answer. Answer the question directly, in "
                "plain prose meant to be READ ALOUD: no markdown, no bullet "
                "points, no headings, no URLs, no citations.\n"
                "THREE OR FOUR SENTENCES. This is going to be spoken to "
                "somebody driving, who cannot skim it and cannot politely "
                "interrupt a paragraph. Say the most interesting true thing "
                "first. If there is more worth telling, STOP and say there is "
                "more — one short clause — rather than telling it now.\n"
                "If the answer depends on something you cannot verify, say so "
                "in the answer itself rather than hedging around it."
            ),
            input=prompt,
            tools=tools,
            max_output_tokens=int(config.DEEP_ANSWER_MAX_TOKENS),
        )
    except Exception as e:
        took = round((time.time() - t0) * 1000, 1)
        print(f"[realtime] deep_dive failed after {took} ms: "
              f"{type(e).__name__}: {e}", flush=True)
        return {"ok": False, "note": f"{type(e).__name__}", "took_ms": took}

    text = (getattr(resp, "output_text", "") or "").strip()
    took = round((time.time() - t0) * 1000, 1)
    if not text:
        return {"ok": False, "note": "empty answer", "took_ms": took}
    return {
        "ok": True, "answer": text, "took_ms": took,
        "model": config.OPENAI_REASONING_MODEL,
        "rules": (
            "Say this in your own voice, and keep it to three or four "
            "sentences. If it ends by saying there is more, offer that in a "
            "short clause rather than continuing into it — the driver can ask "
            "again, and a monologue in a car is one nobody can interrupt."
        ),
    }


# --- the fast path's gate ---------------------------------------------------
# A question that a one-sentence description of the road actually answers.
#
# Deliberately a small list of phrasings rather than a classifier. The router
# can answer "is this a scene question?" properly, and it does for everything
# else — but when its rules are unsure it asks a MODEL, which was measured at
# ~1 s on "what's on the left". Paying a second of remote classification to
# find out whether we may skip two seconds of remote answering is most of the
# saving spent on deciding to save it.
#
# So the fast path is gated on recognising the question, not on understanding
# it: these phrasings mean "describe what is out there" and nothing else, and
# anything not on the list takes the ordinary route through the router.
_GENERIC_SCENE = re.compile(
    r"^\s*(?:so\s+|and\s+|hey\s+|ok(?:ay)?\s+|rio[,\s]+)*"
    r"(?:"
    r"what(?:'?s| is| are| do you| can you)?\s+(?:do\s+you\s+)?see\b"
    r"|what(?:'?s| is)\s+(?:it\s+)?(?:out\s+there|around|going\s+on|happening)\b"
    r"|what(?:'?s| is)\s+(?:the\s+)?(?:road|traffic|scene|view|street)\s+like\b"
    r"|what(?:'?s| is)\s+(?:it\s+)?like\s+out\s+there\b"
    r"|describe\s+(?:the\s+)?(?:road|scene|view|street|surroundings)\b"
    r"|anything\s+i\s+should\s+know\b"
    r"|how(?:'?s| is)\s+(?:the\s+)?(?:road|traffic)\b"
    r")",
    re.IGNORECASE)

# ...and the words that mean this is NOT that question, whatever it looks like.
# A caption says what is out there; it does not say what is on the LEFT, what
# that sign reads, or what colour the third one is. Those need a crop and a
# model that will look at it.
# `right(?!\s+now)`: "what's around us right now" is a scene question, and the
# first version of this list read the "right" in it as a direction and sent the
# most generic question there is down the slow path.
_NEEDS_SPECIFICS = re.compile(
    r"\b(left|right(?!\s+now)|behind|beside|next\s+to|that|those|this|these|sign|says?|"
    r"reads?|colou?r|make|model|plate|licen[cs]e|building|shop|store|logo|"
    r"how\s+far|how\s+many|which)\b",
    re.IGNORECASE)


# How many words a question can run to and still be "what is out there".
# A scene question is short because there is nothing to qualify; anything long
# enough to carry a clause is usually carrying a condition with it, and a
# caption cannot answer a condition.
_SCENE_MAX_WORDS = 12


def is_generic_scene_question(q: str, spoken: str = None) -> bool:
    """May this question be answered from the running observation?

    TWO INPUTS, AND THE FIRST ONE IS THE DRIVER'S.
    ---------------------------------------------
    `q` is what the MODEL passed to the tool, and the model paraphrases: a
    driver who said "what's around us right now" produces a call carrying
    "describe the current scene". The list below was written for the things
    people say, so judging a paraphrase against it fails questions the driver
    asked perfectly well — measured at three of eight, each one costing the
    full remote visual turn (2.3-6.0 s) instead of a 4 ms cache read.

    So `spoken` — the driver's own transcript, which the panel already has and
    now sends — is judged first when it is there, and the paraphrase is the
    fallback rather than the authority.

    AND THE RULE IS NOW THE RIGHT WAY ROUND.
    ----------------------------------------
    It used to be "does this match a list of scene phrasings". That is a
    whitelist, and a whitelist of things people might say is a losing game —
    every phrasing nobody thought of costs two seconds.

    What actually disqualifies a question from being answered by a caption is
    knowable and small: it asks about a PARTICULAR THING. "the black one", "the
    sign", "how far", "what colour". That list is short, closed, and already
    written (_NEEDS_SPECIFICS), and it is what the whitelist was really
    protecting.

    Calling `look` at all is the model asserting the question is visual. Given
    that, a short question with no object reference in it is a scene question,
    and the whitelist survives only as the fast yes for the phrasings it
    already knows.
    """
    for candidate in ((spoken or "").strip(), (q or "").strip()):
        if not candidate:
            continue
        if _NEEDS_SPECIFICS.search(candidate):
            return False
        if _GENERIC_SCENE.search(candidate):
            return True
        if len(candidate.split()) <= _SCENE_MAX_WORDS:
            return True
        return False
    return False


def look(question: str, session_key: str = "default",
         spoken: str = None) -> dict:
    """RIO's eyes: the existing visual pipeline, called from a live session.

    Nothing new is built here. `visual_qa.answer()` is the same path the
    hold-to-talk turn uses — the frame ring, the frame selector, reference
    resolution against tracked objects, the crop, the multimodal turn — and it
    already knows how to say "which one do you mean?" and how to refuse when
    the crop cannot carry the claim being asked for. This wires a tool call to
    it and hands the text back for RIO to speak.

    Imported lazily on purpose: the visual stack pulls in the frame ring, the
    scene tracker and the enrichment cache, and a drive where nobody asks about
    the road should not pay for any of it.

    THE ROUTE OVERRIDE. The visual path classifies the question itself, which
    is what keeps "the black one" working across turns. But the model has
    already decided this question is about what is out there — that is what
    calling `look` MEANS — so a classifier reading it as non-visual is
    overruled here rather than producing an answer with no picture behind it.
    """
    q = (question or "").strip()
    if not q:
        return {"ok": False, "note": "no question"}
    t0 = time.time()
    try:
        import observer
        import router as request_router
        import visual_qa

        session = visual_qa.get_session(session_key)

        # THE FAST PATH, and it comes FIRST -- before the router, because the
        # router is itself a possible remote call and this is the branch that
        # exists to avoid remote calls. Measured: the full turn is ~2.0 s, 99%
        # of it one call to a reasoning model, and the answer to "what do you
        # see" is a sentence the observer wrote about a frame that arrived a
        # moment ago. See observer.py.
        #
        # A pending clarification blocks it: RIO has just asked "which one?",
        # and the next thing the driver says is an answer to that, not a
        # request for the view. Nothing else about the conversation blocks it --
        # in particular, not whether a car was discussed earlier, which was the
        # first version of this condition and made every scene question slow
        # for the rest of a conversation once one object had been mentioned.
        observer.start(session_key)
        observer.touch(session_key)
        # This turn is a look. deep_dive refuses a visual question asked within
        # DEPTH_COLD_S of one -- see depth_allowed().
        note_look(session_key, q)
        if (is_generic_scene_question(q, spoken)
                and session.pending_clarification() is None):
            hit = observer.fresh(session_key)
            if not hit:
                # The background loop is one tick behind frames that ARE
                # current: describe the frame in front of the car now, locally,
                # instead of paying the full remote turn for a question one
                # forward pass would answer. Returns {} when there is no recent
                # frame either, and then the full path says so properly.
                hit = observer.observe_now(session_key)
            if hit:
                took = round((time.time() - t0) * 1000, 1)
                base = {
                    "ok": True,
                    "answer": hit["text"],
                    "took_ms": took,
                    "fast_path": True,
                    "on_demand": bool(hit.get("on_demand")),
                    "seen_s_ago": hit["age_s"],
                }
                # THE SECOND MODEL PASS, AND WHEN IT IS NOT WORTH ITS PRICE.
                #
                # Measured: composing this sentence into another sentence cost
                # ~450 ms of remote model plus the round trip either side of
                # it, on an answer the camera had ready in four milliseconds.
                # For a general question about the road that is most of the
                # wait, and it buys a rephrasing of a line that is already one
                # short sentence.
                #
                # So the observer writes in her register now (see
                # rio_prompts.OBSERVER_PROMPT) and this line is spoken as it
                # stands — but ONLY if it passes persona.lint(), which is what
                # makes "never a raw caption" a check rather than a hope. A
                # line that fails goes back to being composed by her, which is
                # slower and still correct.
                if hit.get("speakable"):
                    base["speak_directly"] = True
                    base["speech"] = hit["text"]
                    base["path"] = "observer_direct"
                    base["rules"] = (
                        "This has ALREADY BEEN SAID to the driver, out loud, "
                        "in your voice. Do not say it again and do not "
                        "acknowledge it. It is here so you know what they just "
                        "heard."
                    )
                    return base
                base["path"] = "observer_composed"
                base["lint"] = hit.get("faults") or []
                base["rules"] = (
                    "This is what the camera is seeing right now — "
                    f"{hit['age_s']:.0f} second(s) ago. Say it in your own "
                    "words, in ONE short sentence, as the road in front of "
                    "you. Do not read it out as a caption and do not add "
                    "anything it does not contain. If the driver wants "
                    "detail about one particular thing, ask this tool again "
                    "about that thing and it will look properly. This is a "
                    "passing scene, so do not offer to say more about it."
                )
                return base

        route = request_router.classify(
            q,
            has_referent=session.active_referent() is not None,
            pending_clarification=session.pending_clarification() is not None)
        if not request_router.is_visual(route["request_type"]):
            # The model has already decided this question is about what is out
            # there -- that is what calling `look` MEANS -- so a classifier
            # reading it as non-visual is overruled rather than producing an
            # answer with no picture behind it.
            route = dict(route, request_type=request_router.SCENE,
                         requires_full_frame=True, requires_object_crop=False,
                         method="forced_by_look_tool")
        # The observer yields to the LOCAL half of this turn and only to that
        # half. prepare() resolves the reference, crops, and runs Qwen for
        # colour and body style -- the same GPU, and the question somebody is
        # waiting for wins it. text() is a remote call and leaves the card
        # idle, which is the best second in the whole turn to describe the road:
        # holding through it starved the observer so thoroughly that the fast
        # path stopped hitting at all, each slow answer making the next question
        # slow too.
        with observer.hold(session_key):
            va = visual_qa.answer(session_key, q, route)
        text = (va.text() or "").strip()
    except Exception as e:
        took = round((time.time() - t0) * 1000, 1)
        print(f"[realtime] look failed after {took} ms: "
              f"{type(e).__name__}: {e}", flush=True)
        return {"ok": False, "note": f"{type(e).__name__}", "took_ms": took}

    took = round((time.time() - t0) * 1000, 1)
    if not text:
        # No frames in the ring is the ordinary version of this: the drive has
        # not started, or the camera is not running. RIO says she cannot see
        # rather than describing a road she has not been shown.
        return {"ok": False, "note": "nothing to see", "took_ms": took}
    return {
        "ok": True, "answer": text, "took_ms": took,
        # Which of the three ways this answer was reached. Logged per call, so
        # "the camera got slow again" is answerable from a drive rather than
        # from a re-measurement: a run that used to be mostly observer_direct
        # and is now mostly full_visual has a different problem from one that
        # is slow at every stage.
        "path": "full_visual",
        "meta": getattr(va, "meta", None),
        "rules": (
            "FIRST ANSWER, AND IT IS SHORT: one or two sentences, in your own "
            "words, from what is here and nothing else. Do not research this "
            "and do not go away and think about it — the driver asked what "
            "something is, not for an essay, and they are driving.\n"
            "If it is the kind of thing there is plausibly more to say about — "
            "a landmark, a named building, an unusual vehicle — you may add ONE "
            "short clause offering it: 'want to know more about it?'. Not every "
            "time, and not for ordinary traffic or an empty road, where there "
            "is nothing to offer and asking is noise."
        ),
    }


def vehicle_status() -> dict:
    """How the car is — from the builder the conversation path already uses.

    `vehicle_health.context(full=True)` is not a summary written for this tool.
    It is the SAME normalised structure that goes into an ordinary
    conversation turn when the router decides a question is about the car
    (llm_interface._health_block), which is what keeps a live answer and a
    hold-to-talk answer from disagreeing about the same tire.

    It carries its own provenance — every issue says who reported it, the
    vehicle's own computer or RIO — and its own limits, including how far back
    the data actually goes. Both survive into the tool result untouched,
    because a model that is handed "26 PSI" with no history and no source will
    happily supply both.
    """
    t0 = time.time()
    try:
        import vehicle_health

        ctx = vehicle_health.context(full=True)
    except Exception as e:
        print(f"[realtime] vehicle_status failed: {type(e).__name__}: {e}", flush=True)
        return {"ok": False, "note": f"{type(e).__name__}"}
    body = ctx.get("vehicle_health", ctx)
    if not body.get("data_available", True) and not body.get("issues"):
        # Nothing is reporting. That is an answer, and a specific one: RIO says
        # she is not getting data rather than that the car is fine.
        return {"ok": True, "vehicle": body, "took_ms": round((time.time() - t0) * 1000, 1),
                "note": "no subsystem is reporting — say that, do not say the car is fine"}
    return {"ok": True, "vehicle": body,
            "took_ms": round((time.time() - t0) * 1000, 1),
            "rules": ("Only claims this data supports. Keep who reported what. "
                      "A code detected but not confirmed stays not confirmed.")}


def run_tool(name: str, arguments, session_key: str = "default",
             where=None, spoken: str = None) -> dict:
    """Dispatch one tool call from the live session.

    An unknown tool name is answered, not raised: the session is a model and a
    model can produce a name that is not in its own tool list. `ok: false` is a
    thing RIO already knows how to handle, and a 500 is not.

    `where` is the car's last GPS fix, attached by the panel to every tool call.
    Only find_places reads it, and only as a location bias -- the browser is the
    one that knows where the car is, for the same reason nav_status is answered
    there.

    `spoken` is the driver's own last transcript, attached the same way and for
    the same kind of reason: the panel is where Whisper's output lands, and the
    visual fast path is a judgement about what was ASKED rather than about how
    the model chose to relay it.
    """
    if name == VEHICLE_TOOL_NAME:
        return vehicle_status()
    if name == NAV_TOOL_NAME:
        # Answered in the BROWSER, where the route tracker lives — the server
        # holds the route but not the progress along it, and inventing a second
        # source for "how far to the next turn" is how two answers to one
        # question happen. See rio_realtime.js: local tools.
        return {"ok": False, "note": "nav_status is answered by the panel"}
    if name == NAV_DIRECTIONS_TOOL_NAME:
        # Same reason as nav_status, one step further: the route lives on the
        # server but WHERE ALONG IT WE ARE does not, and "how far to the turn
        # after next" is a question about both. The server could answer it from
        # the route alone and would be measuring from the start of the drive.
        return {"ok": False, "note": "nav_directions is answered by the panel"}
    if name == NAVIGATE_TOOL_NAME:
        # Also the browser, and for a stronger reason than nav_status: this
        # one is not a read. The server can resolve a destination — it does,
        # at /nav/destination, which is what the panel calls — but it cannot
        # make the car navigate to it, because the route is loaded and tracked
        # in the page. A second implementation here could only resolve and
        # hope, which is the arrangement this tool exists to end.
        return {"ok": False, "note": "start_navigation is answered by the panel"}
    if name not in (TOOL_NAME, LOOK_TOOL_NAME, PLACES_TOOL_NAME):
        return {"ok": False, "note": "unknown tool"}
    if isinstance(arguments, str):
        try:
            arguments = json.loads(arguments or "{}")
        except json.JSONDecodeError:
            return {"ok": False, "note": "unreadable arguments"}
    if not isinstance(arguments, dict):
        return {"ok": False, "note": "unreadable arguments"}
    if name == LOOK_TOOL_NAME:
        # `spoken` is the driver's own last transcript, attached by the panel.
        # The model paraphrases what it was asked, and the fast path is a
        # judgement about the QUESTION, so it is judged on the words that were
        # actually said wherever they are available. See look().
        return look(str(arguments.get("question") or ""), session_key,
                    spoken=str(spoken or "") or None)
    if name == PLACES_TOOL_NAME:
        return places.find_places(
            query=str(arguments.get("query") or ""),
            near=str(arguments.get("near") or ""),
            open_now=bool(arguments.get("open_now")),
            count=arguments.get("count"),
            where=where, session_key=session_key)
    q = str(arguments.get("question") or "")
    ctx = str(arguments.get("context") or "")
    gate = depth_allowed(session_key, q, ctx)
    if not gate["allowed"]:
        # Refused, briefly, with what to do instead. The model gets an answer
        # rather than an error, and the answer is "you already have one".
        return {
            "ok": False,
            "note": "not for first-look questions",
            "reason": gate["reason"],
            "rules": (
                "This is a first look, not research. Answer from what the "
                "camera gave you — one or two short sentences, in your own "
                "words — and if there is plausibly more to say, offer it in a "
                "short clause: 'want to know more about it?'. If the driver "
                "then asks, call this again and it will run."
            ),
        }
    return escalate(q, ctx)


def _observer_status() -> dict:
    try:
        import observer

        return {"enabled": bool(config.OBSERVER_ENABLED),
                "period_s": config.OBSERVER_PERIOD_S,
                "fresh_s": config.OBSERVER_FRESH_S,
                "sessions": observer.status()}
    except Exception as e:
        return {"error": f"{type(e).__name__}"}


def status() -> dict:
    """What the panel and /health need to know, without calling anything."""
    return {
        "enabled": bool(config.REALTIME_ENABLED),
        "model": config.OPENAI_REALTIME_MODEL,
        "voice": config.OPENAI_REALTIME_VOICE,
        "reasoning_model": config.OPENAI_REASONING_MODEL,
        "tools": [TOOL_NAME, LOOK_TOOL_NAME, NAV_TOOL_NAME,
                  NAV_DIRECTIONS_TOOL_NAME, PLACES_TOOL_NAME,
                  VEHICLE_TOOL_NAME, NAVIGATE_TOOL_NAME],
        "web_search": bool(config.REALTIME_WEB_SEARCH),
        # What the running observer is doing, if anything. A live session that
        # feels slow on visual questions is either not observing or observing
        # something stale, and both are visible here.
        "observer": _observer_status(),
        "tool_timeout_s": float(config.REALTIME_TOOL_TIMEOUT_S),
        "key_present": bool(os.getenv("OPENAI_API_KEY", "").strip()),
    }
